import { unreachable } from "../util";
import { TactASTStore } from "./astStore";
import { IdxGenerator } from "./indices";
import { MistiContext } from "../../";
import { Logger } from "../../internals/logger";
import { forEachExpression } from "../tact/iterators";
import {
  AstFunctionDef,
  AstReceiver,
  AstContractInit,
  AstExpression,
  AstMethodCall,
  AstStaticCall,
} from "@tact-lang/compiler/dist/grammar/ast";

export type CGNodeId = number & { readonly brand: unique symbol };
type CGEdgeId = number & { readonly brand: unique symbol };

/**
 * Represents an edge in the call graph, indicating a call from one function to another.
 */
class CGEdge {
  public idx: CGEdgeId;

  constructor(
    public src: CGNodeId,
    public dst: CGNodeId,
  ) {
    this.idx = IdxGenerator.next("cg_edge") as CGEdgeId;
  }
}

/**
 * Represents a node in the call graph, corresponding to a function or method.
 */
class CGNode {
  public idx: CGNodeId;
  public inEdges: Set<CGEdgeId> = new Set();
  public outEdges: Set<CGEdgeId> = new Set();

  /**
   * @param astId AST id of the relevant function definition. It might be `undefined` if this node doesn’t have a corresponding AST entry,
   * which indicates an issue in Misti.
   */
  constructor(
    public astId: number | undefined,
    public name: string,
    private logger: Logger,
  ) {
    this.idx = IdxGenerator.next("cg_node") as CGNodeId;
    if (astId === undefined) {
      this.logger.debug(`CGNode created without AST ID for function "${name}"`);
    }
  }
}

/**
 * The `CallGraph` class represents a directed graph where nodes correspond to functions
 * or methods in a program, and edges indicate calls between them.
 *
 * Nodes and edges are uniquely identified using indices generated by `IdxGenerator`.
 * This class provides methods to construct the graph from AST data, retrieve nodes and edges,
 * and check connectivity between nodes.
 */
export class CallGraph {
  private nodeMap: Map<CGNodeId, CGNode> = new Map();
  private edgesMap: Map<CGEdgeId, CGEdge> = new Map();
  private nameToNodeId: Map<string, CGNodeId> = new Map();
  private logger: Logger;

  constructor(private ctx: MistiContext) {
    this.logger = ctx.logger;
  }

  public getNodes(): Map<CGNodeId, CGNode> {
    return this.nodeMap;
  }

  public getEdges(): Map<CGEdgeId, CGEdge> {
    return this.edgesMap;
  }

  /**
   * Retrieves the node ID associated with a given function name.
   * @param name The function name.
   * @returns The corresponding node ID, or undefined if not found.
   */
  public getNodeIdByName(name: string): CGNodeId | undefined {
    return this.nameToNodeId.get(name);
  }

  /**
   * Retrieves a node from the graph by its ID.
   * @param nodeId The ID of the node.
   * @returns The `CGNode` instance, or undefined if not found.
   */
  public getNode(nodeId: CGNodeId): CGNode | undefined {
    return this.nodeMap.get(nodeId);
  }

  /**
   * Retrieves an edge from the graph by its ID.
   * @param edgeId The ID of the edge.
   * @returns The `CGEdge` instance, or undefined if not found.
   */
  public getEdge(edgeId: CGEdgeId): CGEdge | undefined {
    return this.edgesMap.get(edgeId);
  }

  /**
   * Builds the call graph based on functions in the provided AST store.
   * @param astStore - The AST store containing functions to be added to the graph.
   * @returns The constructed `CallGraph`.
   */
  public build(astStore: TactASTStore): CallGraph {
    for (const func of astStore.getFunctions()) {
      const funcName = this.getFunctionName(func);
      if (funcName) {
        const node = new CGNode(func.id, funcName, this.logger);
        this.nodeMap.set(node.idx, node);
        this.nameToNodeId.set(funcName, node.idx);
      } else {
        this.logger.error(
          `Function with id ${func.id} has no name and will be skipped.`,
        );
      }
    }
    this.analyzeFunctionCalls(astStore);
    return this;
  }

  /**
   * Analyzes function calls in the AST store and adds corresponding edges in the call graph.
   * @param astStore The AST store to analyze for function calls.
   */
  private analyzeFunctionCalls(astStore: TactASTStore) {
    for (const func of astStore.getFunctions()) {
      const funcName = this.getFunctionName(func);
      if (funcName) {
        const callerId = this.nameToNodeId.get(funcName);
        if (callerId !== undefined) {
          forEachExpression(func, (expr) =>
            this.processExpression(expr, callerId),
          );
        } else {
          this.logger.warn(
            `Caller function ${funcName} not found in node map.`,
          );
        }
      }
    }
  }

  /**
   * Extracts the function name based on its type.
   * @param func The function definition, receiver, or contract initializer.
   * @returns The function name if available; otherwise, `undefined`.
   */
  private getFunctionName(
    func: AstFunctionDef | AstReceiver | AstContractInit,
  ): string | undefined {
    switch (func.kind) {
      case "function_def":
        return func.name?.text;
      case "contract_init":
        return `contract_init_${func.id}`;
      case "receiver":
        return `receiver_${func.id}`;
      default:
        unreachable(func);
    }
  }

  /**
   * Processes an expression, identifying static and method calls to add edges.
   * @param expr The AST expression to process.
   * @param callerId The ID of the calling node.
   */
  private processExpression(expr: AstExpression, callerId: CGNodeId) {
    if (expr.kind === "static_call") {
      const staticCall = expr as AstStaticCall;
      const functionName = staticCall.function?.text;
      if (functionName) {
        const calleeId = this.findOrAddFunction(functionName);
        this.addEdge(callerId, calleeId);
      } else {
        this.logger.warn(
          `Static call expression missing function name at caller ${callerId}`,
        );
      }
    } else if (expr.kind === "method_call") {
      const methodCall = expr as AstMethodCall;
      const methodName = methodCall.method?.text;
      if (methodName) {
        const calleeId = this.findOrAddFunction(methodName);
        this.addEdge(callerId, calleeId);
      } else {
        this.logger.warn(
          `Method call expression missing method name at caller ${callerId}`,
        );
      }
    }
  }

  /**
   * Finds or adds a function to the call graph by name.
   * @param name The name of the function to find or add.
   * @returns The ID of the found or added function node.
   */
  private findOrAddFunction(name: string): CGNodeId {
    const nodeId = this.nameToNodeId.get(name);
    if (nodeId !== undefined) {
      return nodeId;
    }
    const newNode = new CGNode(undefined, name, this.logger);
    this.nodeMap.set(newNode.idx, newNode);
    this.nameToNodeId.set(name, newNode.idx);
    return newNode.idx;
  }

  /**
   * Adds an edge between two nodes in the call graph.
   * @param src The source node ID.
   * @param dst The destination node ID.
   */
  private addEdge(src: CGNodeId, dst: CGNodeId) {
    const srcNode = this.nodeMap.get(src);
    const dstNode = this.nodeMap.get(dst);
    if (srcNode && dstNode) {
      const edge = new CGEdge(src, dst);
      this.edgesMap.set(edge.idx, edge);
      srcNode.outEdges.add(edge.idx);
      dstNode.inEdges.add(edge.idx);
    } else {
      this.logger.warn(
        `Cannot add edge from ${src} to ${dst}: node(s) not found.`,
      );
    }
  }
}
