graph TD
    node_1["reply"]
    node_2["notify"]
    node_3["forward"]
    node_4["tWhile"]
    node_5["tRepeat"]
    node_6["tUntil"]
    node_7["tForeach"]
    node_8["tNested"]
    node_9["contract_init_1801"]
    node_10["exampleWhileLoop"]
    node_11["testReply"]
    node_12["sender"]
    node_13["context"]
    node_14["myBalance"]
    node_15["nativeReserve"]
    node_16["send"]
    node_17["emptyMap"]
    node_18["toCell"]
    node_1 --> node_3
    node_1 --> node_12
    node_2 --> node_3
    node_2 --> node_12
    node_3 --> node_13
    node_3 --> node_14
    node_3 --> node_15
    node_3 --> node_16
    node_3 --> node_16
    node_4 --> node_16
    node_4 --> node_12
    node_5 --> node_16
    node_5 --> node_12
    node_6 --> node_16
    node_6 --> node_12
    node_7 --> node_17
    node_7 --> node_16
    node_7 --> node_12
    node_8 --> node_16
    node_8 --> node_12
    node_10 --> node_16
    node_10 --> node_18
    node_11 --> node_1
    node_11 --> node_18
