graph TD
subgraph Test__test
    Test__test_142["m.set(3, 3)"]
    Test__test_143["m.del(3)"]
    Test__test_145["a += 1"]
    Test__test_147["a = 42"]
    Test__test_149["let _b: Int? = m.get(3)"]
    Test__test_151["self.m.set(3, 3)"]:::exitNode
    Test__test_142 --> Test__test_143
    Test__test_143 --> Test__test_145
    Test__test_145 --> Test__test_147
    Test__test_147 --> Test__test_149
    Test__test_149 --> Test__test_151
end
subgraph Test__testOnce
    Test__testOnce_153["m.set(1, 1)"]
    Test__testOnce_154["m.set(2, 2)"]:::exitNode
    Test__testOnce_153 --> Test__testOnce_154
end
