graph TD
subgraph Test__test
    Test__test_146["m.set(3, 3)"]
    Test__test_147["a += 1"]
    Test__test_149["a = 42"]
    Test__test_151["let _b: Int? = m.get(3)"]
    Test__test_153["self.m.set(3, 3)"]:::exitNode
    Test__test_146 --> Test__test_147
    Test__test_147 --> Test__test_149
    Test__test_149 --> Test__test_151
    Test__test_151 --> Test__test_153
end
subgraph Test__testOnce
    Test__testOnce_155["m.set(1, 1)"]
    Test__testOnce_156["m.set(2, 2)"]:::exitNode
    Test__testOnce_155 --> Test__testOnce_156
end
subgraph Test__testForeach
    Test__testForeach_158["foreach ((key, value) of m)"]
    Test__testForeach_159["m.set(3, 3)"]
    Test__testForeach_158 --> Test__testForeach_159
    Test__testForeach_159 --> Test__testForeach_158
end
subgraph Test__id
    Test__id_162["return m"]:::exitNode
end
subgraph Test__testReturn1
    Test__testReturn1_163["m.set(3, 3)"]
    Test__testReturn1_164["if (WHATEVER == 0)"]
    Test__testReturn1_166["return m"]:::exitNode
    Test__testReturn1_168["return self.id(m)"]:::exitNode
    Test__testReturn1_163 --> Test__testReturn1_164
    Test__testReturn1_164 --> Test__testReturn1_166
    Test__testReturn1_164 --> Test__testReturn1_168
end
subgraph Test__testReturn2
    Test__testReturn2_170["m.set(3, 3)"]
    Test__testReturn2_171["if (WHATEVER == 0)"]
    Test__testReturn2_173["return m"]:::exitNode
    Test__testReturn2_175["let mCopy: map&lt;Int, Int&gt; = m"]
    Test__testReturn2_177["return mCopy"]:::exitNode
    Test__testReturn2_170 --> Test__testReturn2_171
    Test__testReturn2_171 --> Test__testReturn2_173
    Test__testReturn2_171 --> Test__testReturn2_175
    Test__testReturn2_175 --> Test__testReturn2_177
end
