graph TD
subgraph test
    test_141["let a: Int = 42"]
    test_142["if (a == 42)"]
    test_144["a = 44"]:::exitNode
    test_146["a = 43"]:::exitNode
    test_141 --> test_142
    test_142 --> test_144
    test_142 --> test_146
end
