graph TD
subgraph refs_num_bad
    refs_num_bad_68["let b1 = beginCell()"]
    refs_num_bad_69["b1 = b1.storeRef(c)"]
    refs_num_bad_70["b1 = b1.storeRef(c)"]
    refs_num_bad_71["b1 = b1.storeRef(c)"]
    refs_num_bad_72["b1 = b1.storeRef(c)"]
    refs_num_bad_73["b1 = b1.storeRef(c)"]
    refs_num_bad_74["let c1 = b1.endCell()"]
    refs_num_bad_75["let c2 = beginCell().storeRef(c).storeRef(c).storeRef(c).storeRef(c).storeRef(c).endCell()"]:::exitNode
    refs_num_bad_68 --> refs_num_bad_69
    refs_num_bad_69 --> refs_num_bad_70
    refs_num_bad_70 --> refs_num_bad_71
    refs_num_bad_71 --> refs_num_bad_72
    refs_num_bad_72 --> refs_num_bad_73
    refs_num_bad_73 --> refs_num_bad_74
    refs_num_bad_74 --> refs_num_bad_75
end
subgraph store_size_bad
    store_size_bad_76["let b1 = beginCell()"]
    store_size_bad_77["b1 = b1.storeInt(42, 257)"]
    store_size_bad_78["b1 = b1.storeInt(42, 259 - 2)"]
    store_size_bad_79["b1 = b1.storeInt(42, 256 + 1)"]
    store_size_bad_80["b1 = b1.storeInt(42, 257)"]
    store_size_bad_81["let c1 = b1.endCell()"]
    store_size_bad_82["let b2 = beginCell()"]
    store_size_bad_83["b2 = b2.storeInt(1, 257).storeInt(1, 257).storeInt(1, 257).storeInt(1, 210)"]
    store_size_bad_84["b2 = b2.storeCoins(40000000000)"]
    store_size_bad_85["c1 = b2.endCell()"]
    store_size_bad_86["let b_1000_bits = beginCell().storeInt(1, 257).storeInt(1, 257).storeInt(1, 257).storeInt(1, 229)"]
    store_size_bad_87["let b3 = beginCell()"]
    store_size_bad_88["b3 = b3.storeBuilder(b_1000_bits).storeInt(1, 25)"]
    store_size_bad_89["c1 = b3.endCell()"]:::exitNode
    store_size_bad_76 --> store_size_bad_77
    store_size_bad_77 --> store_size_bad_78
    store_size_bad_78 --> store_size_bad_79
    store_size_bad_79 --> store_size_bad_80
    store_size_bad_80 --> store_size_bad_81
    store_size_bad_81 --> store_size_bad_82
    store_size_bad_82 --> store_size_bad_83
    store_size_bad_83 --> store_size_bad_84
    store_size_bad_84 --> store_size_bad_85
    store_size_bad_85 --> store_size_bad_86
    store_size_bad_86 --> store_size_bad_87
    store_size_bad_87 --> store_size_bad_88
    store_size_bad_88 --> store_size_bad_89
end
subgraph refs_num_ok
    refs_num_ok_90["let c1 = beginCell().storeRef(c).storeRef(c).storeRef(c).storeMaybeRef(copt).storeRef(c).endCell()"]
    refs_num_ok_91["let b1 = beginCell()"]
    refs_num_ok_92["b1.storeRef(c)"]
    refs_num_ok_93["b1.storeRef(c)"]
    refs_num_ok_94["b1.storeRef(c)"]
    refs_num_ok_95["b1.storeRef(c)"]
    refs_num_ok_96["b1.storeRef(c)"]
    refs_num_ok_97["c1 = b1.endCell()"]:::exitNode
    refs_num_ok_90 --> refs_num_ok_91
    refs_num_ok_91 --> refs_num_ok_92
    refs_num_ok_92 --> refs_num_ok_93
    refs_num_ok_93 --> refs_num_ok_94
    refs_num_ok_94 --> refs_num_ok_95
    refs_num_ok_95 --> refs_num_ok_96
    refs_num_ok_96 --> refs_num_ok_97
end
