graph TD
subgraph test1
    test1_141["let a: Int = 42"]
    test1_142["dump(a)"]
    test1_144["dump(42)"]
    test1_146["dump('test is called')"]
    test1_148["dump(false)"]
    test1_150["dump(null)"]:::exitNode
    test1_141 --> test1_142
    test1_142 --> test1_144
    test1_144 --> test1_146
    test1_146 --> test1_148
    test1_148 --> test1_150
end
