graph TD
subgraph test
    test_68["let a: Int = 1"]
    test_69["a = A &gt; 5 ? A &gt; 5 ? 1 : 2 : 3"]
    test_70["a = A &gt; 5 ? 3 : A &gt; 5 ? 1 : 2"]
    test_71["if (A &gt; 5)"]
    test_72["a = 1"]
    test_73["return a"]:::exitNode
    test_68 --> test_69
    test_69 --> test_70
    test_70 --> test_71
    test_71 --> test_72
    test_72 --> test_73
end
