graph TD
subgraph test1
    test1_141["if (false)"]
    test1_142["while (false)"]
    test1_145["until (false)"]
    test1_148["repeat (0)"]
    test1_151["if (false)"]
    test1_153["return 1"]:::exitNode
    test1_155["if (false)"]
    test1_157["return 1"]:::exitNode
    test1_159["while (false)"]
    test1_161["return 1"]:::exitNode
    test1_164["repeat (0)"]
    test1_166["return 1"]:::exitNode
    test1_169["return false && true ? 1 : 2"]:::exitNode
    test1_141 --> test1_142
    test1_142 --> test1_142
    test1_142 --> test1_145
    test1_145 --> test1_145
    test1_145 --> test1_148
    test1_148 --> test1_148
    test1_148 --> test1_151
    test1_151 --> test1_153
    test1_153 --> test1_155
    test1_155 --> test1_157
    test1_157 --> test1_159
    test1_159 --> test1_161
    test1_161 --> test1_159
    test1_159 --> test1_164
    test1_164 --> test1_166
    test1_166 --> test1_164
    test1_164 --> test1_169
end
