graph TD
subgraph Test1__init_1664
    Test1__init_1664_68["self.a = x"]:::exitNode
end
subgraph Test2__init_1689
    Test2__init_1689_69["self.a = x"]:::exitNode
end
subgraph Test2__getB
    Test2__getB_70["return self.b"]:::exitNode
end
