graph TD
subgraph Test1__init_1664
    Test1__init_1664_143["self.a = x"]:::exitNode
end
subgraph Test2__init_1689
    Test2__init_1689_145["self.a = x"]:::exitNode
end
subgraph Test2__getB
    Test2__getB_146["return self.b"]:::exitNode
end
