graph TD
subgraph C__init_1766
    C__init_1766_142["self.m = m"]
    C__init_1766_143["self.a = a"]:::exitNode
    C__init_1766_142 --> C__init_1766_143
end
subgraph C__updateBalance
    C__updateBalance_145["self.balance = 100"]
    C__updateBalance_146["self.balance -= 100"]
    C__updateBalance_148["self.m.set(3, 3)"]
    C__updateBalance_150["self.m.del(3)"]
    C__updateBalance_152["self.a.x = 42"]
    C__updateBalance_154["self.a.x += 42"]
    C__updateBalance_156["self.a.m.set(3, 3)"]
    C__updateBalance_158["self.a.m.del(3)"]:::exitNode
    C__updateBalance_145 --> C__updateBalance_146
    C__updateBalance_146 --> C__updateBalance_148
    C__updateBalance_148 --> C__updateBalance_150
    C__updateBalance_150 --> C__updateBalance_152
    C__updateBalance_152 --> C__updateBalance_154
    C__updateBalance_154 --> C__updateBalance_156
    C__updateBalance_156 --> C__updateBalance_158
end
