graph TD
subgraph C__init_1766
    C__init_1766_68["self.m = m"]
    C__init_1766_69["self.a = a"]:::exitNode
    C__init_1766_68 --> C__init_1766_69
end
subgraph C__updateBalance
    C__updateBalance_70["self.balance = 100"]
    C__updateBalance_71["self.balance -= 100"]
    C__updateBalance_72["self.m.set(3, 3)"]
    C__updateBalance_73["self.m.del(3)"]
    C__updateBalance_74["self.a.x = 42"]
    C__updateBalance_75["self.a.x += 42"]
    C__updateBalance_76["self.a.m.set(3, 3)"]
    C__updateBalance_77["self.a.m.del(3)"]:::exitNode
    C__updateBalance_70 --> C__updateBalance_71
    C__updateBalance_71 --> C__updateBalance_72
    C__updateBalance_72 --> C__updateBalance_73
    C__updateBalance_73 --> C__updateBalance_74
    C__updateBalance_74 --> C__updateBalance_75
    C__updateBalance_75 --> C__updateBalance_76
    C__updateBalance_76 --> C__updateBalance_77
end
subgraph V__updateBalance
    V__updateBalance_78["self.setBalance(100)"]:::exitNode
end
