graph TD
subgraph test1
    test1_68["let sum: Int = 0"]
    test1_69["let i: Int = 0"]
    test1_70["while (i &lt; 10)"]
    test1_71["i = i + 1"]
    test1_72["sum = sum + i"]
    test1_73["return sum"]:::exitNode
    test1_68 --> test1_69
    test1_69 --> test1_70
    test1_70 --> test1_71
    test1_71 --> test1_72
    test1_72 --> test1_70
    test1_70 --> test1_73
end
subgraph test2
    test2_74["let sum: Int = 0"]
    test2_75["let i: Int = 0"]
    test2_76["until (i &lt; 10)"]
    test2_77["i = i + 1"]
    test2_78["sum = sum + i"]
    test2_79["return sum"]:::exitNode
    test2_74 --> test2_75
    test2_75 --> test2_76
    test2_76 --> test2_77
    test2_77 --> test2_78
    test2_78 --> test2_76
    test2_76 --> test2_79
end
subgraph test3
    test3_80["let sum: Int = 0"]
    test3_81["let i: Int = 0"]
    test3_82["repeat (10)"]
    test3_83["i = i + 1"]
    test3_84["sum = sum + i"]
    test3_85["return sum"]:::exitNode
    test3_80 --> test3_81
    test3_81 --> test3_82
    test3_82 --> test3_83
    test3_83 --> test3_84
    test3_84 --> test3_82
    test3_82 --> test3_85
end
subgraph test4
    test4_86["let m: map&lt;Int, Int&gt; = emptyMap()"]
    test4_87["foreach ((k, v) of m)"]
    test4_86 --> test4_87
    test4_87 --> test4_87
end
