graph TD
subgraph test
    test_141["let sum: Int = 0"]
    test_142["let i: Int = 0"]
    test_144["while (i &lt; 10)"]
    test_146["i = i + 1"]
    test_148["sum = sum + i"]
    test_151["return sum"]:::exitNode
    test_141 --> test_142
    test_142 --> test_144
    test_144 --> test_146
    test_146 --> test_148
    test_148 --> test_144
    test_144 --> test_151
end
