graph TD
subgraph ConstantFieldTest__test
    ConstantFieldTest__test_141["send(SendParameters{to: sender(), bounce: true, value: self.val, mode: SendRemainingValue + SendIgnoreErrors})"]:::exitNode
end
