graph TD
subgraph Test__receive_internal_simple_1691
    Test__receive_internal_simple_1691_142["let pkg: Slice = msg.whatever"]
    Test__receive_internal_simple_1691_143["let _seqno: Int = pkg.loadInt(32)"]
    Test__receive_internal_simple_1691_145["let mode: Int = pkg.loadInt(8)"]
    Test__receive_internal_simple_1691_147["let body: Cell = pkg.loadRef()"]
    Test__receive_internal_simple_1691_149["nativeSendMessage(body, mode)"]:::exitNode
    Test__receive_internal_simple_1691_142 --> Test__receive_internal_simple_1691_143
    Test__receive_internal_simple_1691_143 --> Test__receive_internal_simple_1691_145
    Test__receive_internal_simple_1691_145 --> Test__receive_internal_simple_1691_147
    Test__receive_internal_simple_1691_147 --> Test__receive_internal_simple_1691_149
end
subgraph Test__getInt
    Test__getInt_151["return nativeRandom()"]:::exitNode
end
