graph TD
subgraph Test__test
    Test__test_68["let a: Int = 42"]
    Test__test_69["a = a + 1"]
    Test__test_70["a = 1 + a"]
    Test__test_71["self.field = 1 + self.field"]
    Test__test_72["self.field = self.field + a"]
    Test__test_73["self.field = self.field + a + 1"]
    Test__test_74["self.field = -self.field + a"]:::exitNode
    Test__test_68 --> Test__test_69
    Test__test_69 --> Test__test_70
    Test__test_70 --> Test__test_71
    Test__test_71 --> Test__test_72
    Test__test_72 --> Test__test_73
    Test__test_73 --> Test__test_74
end
