graph TD
subgraph Test__test
    Test__test_141["let a: Int = 42"]
    Test__test_142["a = a + 1"]
    Test__test_144["a = 1 + a"]
    Test__test_146["self.field = 1 + self.field"]
    Test__test_148["self.field = self.field + a"]
    Test__test_150["self.field = self.field + a + 1"]
    Test__test_152["self.field = -self.field + a"]:::exitNode
    Test__test_141 --> Test__test_142
    Test__test_142 --> Test__test_144
    Test__test_144 --> Test__test_146
    Test__test_146 --> Test__test_148
    Test__test_148 --> Test__test_150
    Test__test_150 --> Test__test_152
end
