graph TD
subgraph Test__receive_internal_simple_1691
    Test__receive_internal_simple_1691_68["let pkg: Slice = msg.whatever"]
    Test__receive_internal_simple_1691_69["let _seqno: Int = pkg.loadInt(32)"]
    Test__receive_internal_simple_1691_70["let mode: Int = pkg.loadInt(8)"]
    Test__receive_internal_simple_1691_71["let body: Cell = pkg.loadRef()"]
    Test__receive_internal_simple_1691_72["nativeSendMessage(body, mode)"]:::exitNode
    Test__receive_internal_simple_1691_68 --> Test__receive_internal_simple_1691_69
    Test__receive_internal_simple_1691_69 --> Test__receive_internal_simple_1691_70
    Test__receive_internal_simple_1691_70 --> Test__receive_internal_simple_1691_71
    Test__receive_internal_simple_1691_71 --> Test__receive_internal_simple_1691_72
end
subgraph Test__getInt
    Test__getInt_73["return nativeRandom()"]:::exitNode
end
