graph TD
subgraph test
    test_142["let a: Int = 10"]
    test_143["return a"]:::exitNode
    test_142 --> test_143
end
subgraph Test__test
    Test__test_145["let result: Int? = self.m.get(a)"]
    Test__test_146["if (result == 1)"]
    Test__test_148["return true"]:::exitNode
    Test__test_150["return false"]:::exitNode
    Test__test_145 --> Test__test_146
    Test__test_146 --> Test__test_148
    Test__test_148 --> Test__test_150
end
