graph TD
subgraph test1
    test1_146["let a: Int = 10"]
    test1_147["return a"]:::exitNode
    test1_146 --> test1_147
end
subgraph test2
    test2_149["let a: Int = 10"]
    test2_150["repeat (a)"]
    test2_153["repeat (a)"]
    test2_149 --> test2_150
    test2_150 --> test2_150
    test2_150 --> test2_153
    test2_153 --> test2_153
end
subgraph test3
    test3_156["let a: Int = 42"]
    test3_157["if (a == 42)"]:::exitNode
    test3_156 --> test3_157
end
subgraph test4
    test4_159["let a: Int = 10"]
    test4_160["if (a == 42)"]:::exitNode
    test4_159 --> test4_160
end
subgraph test5
    test5_162["let _a: Int = 10"]
    test5_163["if (_a == 42)"]:::exitNode
    test5_162 --> test5_163
end
subgraph Test__test
    Test__test_165["let result: Int? = self.m.get(a)"]
    Test__test_166["if (result == 1)"]
    Test__test_168["return true"]:::exitNode
    Test__test_170["return false"]:::exitNode
    Test__test_165 --> Test__test_166
    Test__test_166 --> Test__test_168
    Test__test_168 --> Test__test_170
end
