graph TD
subgraph test1
    test1_68["let a: Int = 10"]
    test1_69["return a"]:::exitNode
    test1_68 --> test1_69
end
subgraph test2
    test2_70["let a: Int = 10"]
    test2_71["repeat (a)"]
    test2_72["repeat (a)"]
    test2_70 --> test2_71
    test2_71 --> test2_71
    test2_71 --> test2_72
    test2_72 --> test2_72
end
subgraph test3
    test3_73["let a: Int = 42"]
    test3_74["if (a == 42)"]:::exitNode
    test3_73 --> test3_74
end
subgraph test4
    test4_75["let a: Int = 10"]
    test4_76["if (a == 42)"]:::exitNode
    test4_75 --> test4_76
end
subgraph test5
    test5_77["let _a: Int = 10"]
    test5_78["if (_a == 42)"]:::exitNode
    test5_77 --> test5_78
end
subgraph Test__test
    Test__test_79["let result: Int? = self.m.get(a)"]
    Test__test_80["if (result == 1)"]
    Test__test_81["return true"]:::exitNode
    Test__test_82["return false"]:::exitNode
    Test__test_79 --> Test__test_80
    Test__test_80 --> Test__test_81
    Test__test_81 --> Test__test_82
end
