graph TD
subgraph Test__receive_internal_comment_1660_test
end
subgraph Test__receive_internal_simple_1720
    Test__receive_internal_simple_1720_68["if (msg == 'test')"]
    Test__receive_internal_simple_1720_69["if ('test' != msg)"]
    Test__receive_internal_simple_1720_70["if ('test' != msg && WHATEVER)"]
    Test__receive_internal_simple_1720_71["if ((WHATEVER || WHATEVER) && 'test' != msg)"]
    Test__receive_internal_simple_1720_72["let foo: String = msg"]
    Test__receive_internal_simple_1720_73["let bar = foo"]
    Test__receive_internal_simple_1720_74["if ('test' == bar)"]
    Test__receive_internal_simple_1720_75["let test1: String = 'test'"]
    Test__receive_internal_simple_1720_76["let test2 = test1"]
    Test__receive_internal_simple_1720_77["if (test2 == msg)"]
    Test__receive_internal_simple_1720_78["if (test2 != bar)"]
    Test__receive_internal_simple_1720_79["if (bar == test2)"]
    Test__receive_internal_simple_1720_80["if ('test' != a)"]:::exitNode
    Test__receive_internal_simple_1720_68 --> Test__receive_internal_simple_1720_69
    Test__receive_internal_simple_1720_69 --> Test__receive_internal_simple_1720_70
    Test__receive_internal_simple_1720_70 --> Test__receive_internal_simple_1720_71
    Test__receive_internal_simple_1720_71 --> Test__receive_internal_simple_1720_72
    Test__receive_internal_simple_1720_72 --> Test__receive_internal_simple_1720_73
    Test__receive_internal_simple_1720_73 --> Test__receive_internal_simple_1720_74
    Test__receive_internal_simple_1720_74 --> Test__receive_internal_simple_1720_75
    Test__receive_internal_simple_1720_75 --> Test__receive_internal_simple_1720_76
    Test__receive_internal_simple_1720_76 --> Test__receive_internal_simple_1720_77
    Test__receive_internal_simple_1720_77 --> Test__receive_internal_simple_1720_78
    Test__receive_internal_simple_1720_78 --> Test__receive_internal_simple_1720_79
    Test__receive_internal_simple_1720_79 --> Test__receive_internal_simple_1720_80
end
