graph TD
subgraph test
    test_141["let a: Int = 0"]
    test_142["try ... catch (err)"]
    test_144["a = 19"]
    test_146["dump(err)"]:::exitNode
    test_148["return a"]:::exitNode
    test_141 --> test_142
    test_142 --> test_144
    test_142 --> test_146
    test_144 --> test_148
end
