graph TD
subgraph test1
    test1_143["let a: Int = 42"]
    test1_144["try"]
    test1_146["a += 1"]
    test1_148["return 42"]:::exitNode
    test1_143 --> test1_144
    test1_144 --> test1_146
    test1_146 --> test1_148
end
subgraph test2
    test2_150["try"]
    test2_151["return 42"]:::exitNode
    test2_150 --> test2_151
end
subgraph test3
    test3_153["let a: Int = 0"]
    test3_154["try ... catch (err)"]
    test3_156["a = 19"]
    test3_158["dump(err)"]:::exitNode
    test3_160["return a"]:::exitNode
    test3_153 --> test3_154
    test3_154 --> test3_156
    test3_154 --> test3_158
    test3_156 --> test3_160
end
