graph TD
subgraph test1
    test1_68["let a: Int = 20"]
    test1_69["while (a &gt; 10)"]
    test1_70["return a"]:::exitNode
    test1_68 --> test1_69
    test1_69 --> test1_69
    test1_69 --> test1_70
end
subgraph test2
    test2_71["let a: Int = 20"]
    test2_72["until (a &gt; 10)"]
    test2_73["return a"]:::exitNode
    test2_71 --> test2_72
    test2_72 --> test2_72
    test2_72 --> test2_73
end
subgraph test3
    test3_74["let a: Int = 20"]
    test3_75["while (a &gt; 10)"]
    test3_76["a += 1"]
    test3_77["return a"]:::exitNode
    test3_74 --> test3_75
    test3_75 --> test3_76
    test3_76 --> test3_75
    test3_75 --> test3_77
end
subgraph test4
    test4_78["let a: Int = 10"]
    test4_79["repeat (a)"]
    test4_80["return a"]:::exitNode
    test4_78 --> test4_79
    test4_79 --> test4_79
    test4_79 --> test4_80
end
subgraph test5
    test5_81["let i: Int = 0"]
    test5_82["while (i &gt; 0)"]
    test5_81 --> test5_82
    test5_82 --> test5_82
end
subgraph test6
    test6_83["let i: Int = 0"]
    test6_84["while (10 &lt; i)"]
    test6_83 --> test6_84
    test6_84 --> test6_84
end
subgraph test7
    test7_85["let i: Bool = false"]
    test7_86["while (i)"]
    test7_85 --> test7_86
    test7_86 --> test7_86
end
subgraph test8
    test8_87["let i: Bool = true"]
    test8_88["while (!i)"]
    test8_87 --> test8_88
    test8_88 --> test8_88
end
subgraph fn
end
subgraph test9
    test9_89["let a: Int = 20"]
    test9_90["while (a &gt; 10)"]
    test9_91["fn(a)"]
    test9_92["return a"]:::exitNode
    test9_89 --> test9_90
    test9_90 --> test9_91
    test9_91 --> test9_90
    test9_90 --> test9_92
end
subgraph Test__receive_internal_comment_1790_test
    Test__receive_internal_comment_1790_test_93["let s: S = S{a: 1}"]
    Test__receive_internal_comment_1790_test_94["let i: Int = 0"]
    Test__receive_internal_comment_1790_test_95["while (i &lt; s.a)"]
    Test__receive_internal_comment_1790_test_96["i += 1"]
    Test__receive_internal_comment_1790_test_93 --> Test__receive_internal_comment_1790_test_94
    Test__receive_internal_comment_1790_test_94 --> Test__receive_internal_comment_1790_test_95
    Test__receive_internal_comment_1790_test_95 --> Test__receive_internal_comment_1790_test_96
    Test__receive_internal_comment_1790_test_96 --> Test__receive_internal_comment_1790_test_95
end
