graph TD
subgraph test
    test_141["let a: Int = 20"]
    test_142["until (a &gt; 10)"]
    test_145["return a"]:::exitNode
    test_141 --> test_142
    test_142 --> test_142
    test_142 --> test_145
end
