graph TD
subgraph f
    f_68["return 42"]:::exitNode
end
subgraph fOpt
    fOpt_69["return null"]:::exitNode
end
subgraph use
end
subgraph C__receive_internal_simple_1713
    C__receive_internal_simple_1713_70["let _a: Int? = m.field"]
    C__receive_internal_simple_1713_71["self._f4 = m.field"]:::exitNode
    C__receive_internal_simple_1713_70 --> C__receive_internal_simple_1713_71
end
subgraph C__receive_internal_comment_1720_whatever
    C__receive_internal_comment_1720_whatever_72["let _a: Int? = 12"]:::exitNode
end
subgraph C__test
    C__test_73["let _a1: Int? = f()"]
    C__test_74["let _a2: Int? = fOpt()"]
    C__test_75["let _a3: Int? = self.m()"]
    C__test_76["let _a4: Int? = self.mOpt()"]
    C__test_77["let _a5: Int? = 12"]
    C__test_78["let _a6: Int? = 12"]
    C__test_79["!!_a6"]
    C__test_80["let _a7: Int? = 12"]
    C__test_81["if (_a7 == null)"]
    C__test_82["let _a8: Int? = 12"]
    C__test_83["if (null == _a8)"]
    C__test_84["let _a9: Int? = 12"]
    C__test_85["use(_a9)"]
    C__test_86["let _a10: Int = !!self._f1"]
    C__test_87["use(self._f2)"]
    C__test_88["if (self._f3 == null)"]:::exitNode
    C__test_73 --> C__test_74
    C__test_74 --> C__test_75
    C__test_75 --> C__test_76
    C__test_76 --> C__test_77
    C__test_77 --> C__test_78
    C__test_78 --> C__test_79
    C__test_79 --> C__test_80
    C__test_80 --> C__test_81
    C__test_81 --> C__test_82
    C__test_82 --> C__test_83
    C__test_83 --> C__test_84
    C__test_84 --> C__test_85
    C__test_85 --> C__test_86
    C__test_86 --> C__test_87
    C__test_87 --> C__test_88
end
subgraph C__m
    C__m_89["return 42"]:::exitNode
end
subgraph C__mOpt
    C__mOpt_90["return null"]:::exitNode
end
