graph TD
subgraph f
    f_148["return 42"]:::exitNode
end
subgraph fOpt
    fOpt_149["return null"]:::exitNode
end
subgraph use
end
subgraph C__receive_internal_simple_1713
    C__receive_internal_simple_1713_150["let _a: Int? = m.field"]
    C__receive_internal_simple_1713_151["self._f4 = m.field"]:::exitNode
    C__receive_internal_simple_1713_150 --> C__receive_internal_simple_1713_151
end
subgraph C__receive_internal_comment_1720_whatever
    C__receive_internal_comment_1720_whatever_153["let _a: Int? = 12"]:::exitNode
end
subgraph C__test
    C__test_154["let _a1: Int? = f()"]
    C__test_155["let _a2: Int? = fOpt()"]
    C__test_157["let _a3: Int? = self.m()"]
    C__test_159["let _a4: Int? = self.mOpt()"]
    C__test_161["let _a5: Int? = 12"]
    C__test_163["let _a6: Int? = 12"]
    C__test_165["!!_a6"]
    C__test_167["let _a7: Int? = 12"]
    C__test_169["if (_a7 == null)"]
    C__test_171["let _a8: Int? = 12"]
    C__test_173["if (null == _a8)"]
    C__test_175["let _a9: Int? = 12"]
    C__test_177["use(_a9)"]
    C__test_179["let _a10: Int = !!self._f1"]
    C__test_181["use(self._f2)"]
    C__test_183["if (self._f3 == null)"]:::exitNode
    C__test_154 --> C__test_155
    C__test_155 --> C__test_157
    C__test_157 --> C__test_159
    C__test_159 --> C__test_161
    C__test_161 --> C__test_163
    C__test_163 --> C__test_165
    C__test_165 --> C__test_167
    C__test_167 --> C__test_169
    C__test_169 --> C__test_171
    C__test_171 --> C__test_173
    C__test_173 --> C__test_175
    C__test_175 --> C__test_177
    C__test_177 --> C__test_179
    C__test_179 --> C__test_181
    C__test_181 --> C__test_183
end
subgraph C__m
    C__m_185["return 42"]:::exitNode
end
subgraph C__mOpt
    C__mOpt_186["return null"]:::exitNode
end
