graph TD
    node_1["inline extends fun asSlice(self: Builder): Slice"]
    node_2["inline extends fun asSlice(self: Cell): Slice"]
    node_3["inline extends fun asCell(self: Slice): Cell"]
    node_4["inline extends fun asCell(self: Builder): Cell"]
    node_5["inline fun emptyCell(): Cell"]
    node_6["inline fun emptySlice(): Slice"]
    node_7["inline extends fun toCoinsString(self: Int): String"]
    node_8["extends fun asComment(self: String): Cell"]
    node_9["inline extends fun fromBase64(self: String): Slice"]
    node_10["extends fun fromBase64(self: Slice): Slice"]
    node_11["inline fun randomInt(): Int"]
    node_12["inline fun random(min: Int, max: Int): Int"]
    node_13["inline fun contractAddress(s: StateInit): Address"]
    node_14["extends fun readForwardFee(self: Context): Int"]
    node_15["fun send(params: SendParameters): Int"]
    node_16["inline fun emit(body: Cell)"]
    node_17["init(owner: Address, content: Cell, max_supply: Int)
[StateWrite]"]
    node_18["receive(msg: Mint)
[StateRead]"]
    node_19["receive('Mint: 100')
[StateRead]"]
    node_20["receive('Owner: MintClose')
[StateRead,StateWrite]"]
    node_21["init(master: Address, owner: Address)
[StateWrite]"]
    node_22["receive(msg: TokenTransfer)
[Send,StateRead,StateWrite]"]
    node_23["receive(msg: TokenTransferInternal)
[Send,StateRead,StateWrite]"]
    node_24["get fun msgValue(value: Int): Int
[StateRead]"]
    node_25["receive(msg: TokenBurn)
[Send,StateRead,StateWrite]"]
    node_26["bounced(msg: Slice)
[StateWrite]"]
    node_27["get fun get_wallet_data(): JettonWalletData
[StateRead]"]
    node_28["context"]
    node_29["require"]
    node_30["mint"]
    node_31["ctx::readForwardFee"]
    node_32["min"]
    node_33["ton"]
    node_34["toCell"]
    node_35["msgValue"]
    node_36["myBalance"]
    node_37["msg::loadUint"]
    node_38["msg::loadCoins"]
    node_18 --> node_28
    node_18 --> node_29
    node_18 --> node_29
    node_18 --> node_30
    node_19 --> node_28
    node_19 --> node_29
    node_19 --> node_30
    node_20 --> node_28
    node_20 --> node_29
    node_22 --> node_28
    node_22 --> node_29
    node_22 --> node_31
    node_22 --> node_31
    node_22 --> node_29
    node_22 --> node_32
    node_22 --> node_33
    node_22 --> node_29
    node_22 --> node_13
    node_22 --> node_15
    node_22 --> node_34
    node_23 --> node_28
    node_23 --> node_29
    node_23 --> node_13
    node_23 --> node_29
    node_23 --> node_15
    node_23 --> node_34
    node_23 --> node_35
    node_23 --> node_31
    node_23 --> node_15
    node_23 --> node_34
    node_24 --> node_36
    node_24 --> node_32
    node_25 --> node_28
    node_25 --> node_29
    node_25 --> node_29
    node_25 --> node_31
    node_25 --> node_29
    node_25 --> node_15
    node_25 --> node_34
    node_26 --> node_37
    node_26 --> node_37
    node_26 --> node_38
    node_26 --> node_29
