graph TD
    node_15["inline fun contractAddress(s: StateInit): Address"]
    node_29["SampleJetton::init(owner: Address, content: Cell, max_supply: Int)
[StateWrite<totalSupply,max_supply,owner,mintable,content>]"]
    node_30["SampleJetton::receive(msg: Mint)
[StateRead<owner,mintable>]"]
    node_31["SampleJetton::receive('Mint: 100')
[StateRead<mintable,owner>]"]
    node_32["SampleJetton::receive('Owner: MintClose')
[StateRead<owner>,StateWrite<mintable>]"]
    node_33["Jetton::receive(msg: TokenUpdateContent)
[StateWrite<content>]"]
    node_34["Jetton::receive(msg: TokenBurnNotification)
[Send,StateWrite<totalSupply>]"]
    node_35["fun Jetton::mint(to: Address, amount: Int, response_destination: Address)
[Send,StateRead<totalSupply,max_supply>,StateWrite<totalSupply>]"]
    node_36["fun Jetton::requireWallet(owner: Address)"]
    node_37["virtual fun Jetton::getJettonWalletInit(address: Address): StateInit"]
    node_38["get fun Jetton::get_jetton_data(): JettonData
[StateRead<totalSupply,mintable,owner,content>]"]
    node_39["get fun Jetton::get_wallet_address(owner: Address): Address"]
    node_40["JettonDefaultWallet::init(master: Address, owner: Address)
[StateWrite<balance,owner,master>]"]
    node_41["JettonDefaultWallet::receive(msg: TokenTransfer)
[Send,StateRead<owner,gasConsumption,minTonsForStorage,balance,master>,StateWrite<balance>]"]
    node_42["JettonDefaultWallet::receive(msg: TokenTransferInternal)
[Send,StateRead<master,balance,owner>,StateWrite<balance>]"]
    node_43["get fun JettonDefaultWallet::msgValue(value: Int): Int
[StateRead<minTonsForStorage>]"]
    node_44["JettonDefaultWallet::receive(msg: TokenBurn)
[Send,StateRead<owner,balance,gasConsumption,minTonsForStorage,master>,StateWrite<balance>]"]
    node_45["JettonDefaultWallet::bounced(msg: Slice)
[StateWrite<balance>]"]
    node_46["get fun JettonDefaultWallet::get_wallet_data(): JettonWalletData
[StateRead<balance,owner,master>]"]
    node_47["context"]
    node_48["require"]
    node_49["SampleJetton::mint"]
    node_50["Jetton::requireOwner"]
    node_51["send"]
    node_52["myAddress"]
    node_53["emptySlice"]
    node_54["ctx::readForwardFee"]
    node_55["min"]
    node_56["ton"]
    node_57["myBalance"]
    node_58["msg::loadUint"]
    node_59["msg::loadCoins"]
    node_30 --> node_47
    node_30 --> node_48
    node_30 --> node_48
    node_30 --> node_49
    node_31 --> node_47
    node_31 --> node_48
    node_31 --> node_49
    node_32 --> node_47
    node_32 --> node_48
    node_33 --> node_50
    node_34 --> node_36
    node_34 --> node_51
    node_35 --> node_48
    node_35 --> node_37
    node_35 --> node_51
    node_35 --> node_15
    node_35 --> node_52
    node_35 --> node_53
    node_36 --> node_47
    node_36 --> node_37
    node_36 --> node_48
    node_36 --> node_15
    node_37 --> node_52
    node_38 --> node_37
    node_38 --> node_52
    node_39 --> node_37
    node_39 --> node_15
    node_41 --> node_47
    node_41 --> node_48
    node_41 --> node_54
    node_41 --> node_54
    node_41 --> node_48
    node_41 --> node_55
    node_41 --> node_56
    node_41 --> node_48
    node_41 --> node_15
    node_41 --> node_51
    node_42 --> node_47
    node_42 --> node_48
    node_42 --> node_15
    node_42 --> node_48
    node_42 --> node_51
    node_42 --> node_43
    node_42 --> node_54
    node_42 --> node_51
    node_43 --> node_57
    node_43 --> node_55
    node_44 --> node_47
    node_44 --> node_48
    node_44 --> node_48
    node_44 --> node_54
    node_44 --> node_48
    node_44 --> node_51
    node_45 --> node_58
    node_45 --> node_58
    node_45 --> node_59
    node_45 --> node_48
    style node_15 fill:#F0F8FF,stroke:#000,stroke-width:1px;
