graph TD
subgraph SampleJetton__init_1907
    SampleJetton__init_1907_68["self.totalSupply = 0"]
    SampleJetton__init_1907_69["self.max_supply = max_supply"]
    SampleJetton__init_1907_70["self.owner = owner"]
    SampleJetton__init_1907_71["self.mintable = true"]
    SampleJetton__init_1907_72["self.content = content"]:::exitNode
    SampleJetton__init_1907_68 --> SampleJetton__init_1907_69
    SampleJetton__init_1907_69 --> SampleJetton__init_1907_70
    SampleJetton__init_1907_70 --> SampleJetton__init_1907_71
    SampleJetton__init_1907_71 --> SampleJetton__init_1907_72
end
subgraph SampleJetton__receive_internal_simple_1857
    SampleJetton__receive_internal_simple_1857_73["let ctx: Context = context()"]
    SampleJetton__receive_internal_simple_1857_74["require(ctx.sender == self.owner, 'Not Owner')"]
    SampleJetton__receive_internal_simple_1857_75["require(self.mintable, 'Can't Mint Anymore')"]
    SampleJetton__receive_internal_simple_1857_76["self.mint(msg.receiver, msg.amount, self.owner)"]:::exitNode
    SampleJetton__receive_internal_simple_1857_73 --> SampleJetton__receive_internal_simple_1857_74
    SampleJetton__receive_internal_simple_1857_74 --> SampleJetton__receive_internal_simple_1857_75
    SampleJetton__receive_internal_simple_1857_75 --> SampleJetton__receive_internal_simple_1857_76
end
subgraph SampleJetton__receive_internal_comment_1882_Mint__100
    SampleJetton__receive_internal_comment_1882_Mint__100_77["let ctx: Context = context()"]
    SampleJetton__receive_internal_comment_1882_Mint__100_78["require(self.mintable, 'Can't Mint Anymore')"]
    SampleJetton__receive_internal_comment_1882_Mint__100_79["self.mint(ctx.sender, 100, self.owner)"]:::exitNode
    SampleJetton__receive_internal_comment_1882_Mint__100_77 --> SampleJetton__receive_internal_comment_1882_Mint__100_78
    SampleJetton__receive_internal_comment_1882_Mint__100_78 --> SampleJetton__receive_internal_comment_1882_Mint__100_79
end
subgraph SampleJetton__receive_internal_comment_1905_Owner__MintClose
    SampleJetton__receive_internal_comment_1905_Owner__MintClose_80["let ctx: Context = context()"]
    SampleJetton__receive_internal_comment_1905_Owner__MintClose_81["require(ctx.sender == self.owner, 'Not Owner')"]
    SampleJetton__receive_internal_comment_1905_Owner__MintClose_82["self.mintable = false"]:::exitNode
    SampleJetton__receive_internal_comment_1905_Owner__MintClose_80 --> SampleJetton__receive_internal_comment_1905_Owner__MintClose_81
    SampleJetton__receive_internal_comment_1905_Owner__MintClose_81 --> SampleJetton__receive_internal_comment_1905_Owner__MintClose_82
end
subgraph JettonDefaultWallet__init_2910
    JettonDefaultWallet__init_2910_83["self.balance = 0"]
    JettonDefaultWallet__init_2910_84["self.owner = owner"]
    JettonDefaultWallet__init_2910_85["self.master = master"]:::exitNode
    JettonDefaultWallet__init_2910_83 --> JettonDefaultWallet__init_2910_84
    JettonDefaultWallet__init_2910_84 --> JettonDefaultWallet__init_2910_85
end
subgraph JettonDefaultWallet__receive_internal_simple_2517
    JettonDefaultWallet__receive_internal_simple_2517_86["let ctx: Context = context()"]
    JettonDefaultWallet__receive_internal_simple_2517_87["require(ctx.sender == self.owner, 'Invalid sender')"]
    JettonDefaultWallet__receive_internal_simple_2517_88["let fwdFee: Int = ctx.readForwardFee() + ctx.readForwardFee()"]
    JettonDefaultWallet__receive_internal_simple_2517_89["let final: Int = 2 * self.gasConsumption + self.minTonsForStorage + fwdFee"]
    JettonDefaultWallet__receive_internal_simple_2517_90["require(ctx.value &gt; min(final, ton('0.01')), 'Invalid value!!')"]
    JettonDefaultWallet__receive_internal_simple_2517_91["self.balance = self.balance - msg.amount"]
    JettonDefaultWallet__receive_internal_simple_2517_92["require(self.balance &gt;= 0, 'Invalid balance')"]
    JettonDefaultWallet__receive_internal_simple_2517_93["let init: StateInit = initOf JettonDefaultWallet(self.master, msg.destination)"]
    JettonDefaultWallet__receive_internal_simple_2517_94["let walletAddress: Address = contractAddress(init)"]
    JettonDefaultWallet__receive_internal_simple_2517_95["send(SendParameters{to: walletAddress, value: 0, mode: SendRemainingValue, bounce: false, body: TokenTransferInternal{queryId: msg.queryId, amount: msg.amount, from: self.owner, response_destination: msg.response_destination, forward_ton_amount: msg.forward_ton_amount, forward_payload: msg.forward_payload}.toCell(), code: init.code, data: init.data})"]:::exitNode
    JettonDefaultWallet__receive_internal_simple_2517_86 --> JettonDefaultWallet__receive_internal_simple_2517_87
    JettonDefaultWallet__receive_internal_simple_2517_87 --> JettonDefaultWallet__receive_internal_simple_2517_88
    JettonDefaultWallet__receive_internal_simple_2517_88 --> JettonDefaultWallet__receive_internal_simple_2517_89
    JettonDefaultWallet__receive_internal_simple_2517_89 --> JettonDefaultWallet__receive_internal_simple_2517_90
    JettonDefaultWallet__receive_internal_simple_2517_90 --> JettonDefaultWallet__receive_internal_simple_2517_91
    JettonDefaultWallet__receive_internal_simple_2517_91 --> JettonDefaultWallet__receive_internal_simple_2517_92
    JettonDefaultWallet__receive_internal_simple_2517_92 --> JettonDefaultWallet__receive_internal_simple_2517_93
    JettonDefaultWallet__receive_internal_simple_2517_93 --> JettonDefaultWallet__receive_internal_simple_2517_94
    JettonDefaultWallet__receive_internal_simple_2517_94 --> JettonDefaultWallet__receive_internal_simple_2517_95
end
subgraph JettonDefaultWallet__receive_internal_simple_2687
    JettonDefaultWallet__receive_internal_simple_2687_96["let ctx: Context = context()"]
    JettonDefaultWallet__receive_internal_simple_2687_97["if (ctx.sender != self.master)"]
    JettonDefaultWallet__receive_internal_simple_2687_98["let sInit: StateInit = initOf JettonDefaultWallet(self.master, msg.from)"]
    JettonDefaultWallet__receive_internal_simple_2687_99["require(contractAddress(sInit) == ctx.sender, 'Invalid sender!')"]
    JettonDefaultWallet__receive_internal_simple_2687_100["self.balance = self.balance + msg.amount"]
    JettonDefaultWallet__receive_internal_simple_2687_101["require(self.balance &gt;= 0, 'Invalid balance')"]
    JettonDefaultWallet__receive_internal_simple_2687_102["if (msg.forward_ton_amount &gt; 0)"]
    JettonDefaultWallet__receive_internal_simple_2687_103["send(SendParameters{to: self.owner, value: msg.forward_ton_amount, bounce: false, body: TokenNotification{queryId: msg.queryId, amount: msg.amount, from: msg.from, forward_payload: msg.forward_payload}.toCell()})"]
    JettonDefaultWallet__receive_internal_simple_2687_104["let msgValue: Int = self.msgValue(ctx.value)"]
    JettonDefaultWallet__receive_internal_simple_2687_105["let fwdFee: Int = ctx.readForwardFee()"]
    JettonDefaultWallet__receive_internal_simple_2687_106["msgValue = msgValue - msg.forward_ton_amount - fwdFee"]
    JettonDefaultWallet__receive_internal_simple_2687_107["if (msg.response_destination != null)"]
    JettonDefaultWallet__receive_internal_simple_2687_108["send(SendParameters{to: !!msg.response_destination, value: msgValue, bounce: false, body: TokenExcesses{queryId: msg.queryId}.toCell(), mode: SendIgnoreErrors})"]:::exitNode
    JettonDefaultWallet__receive_internal_simple_2687_96 --> JettonDefaultWallet__receive_internal_simple_2687_97
    JettonDefaultWallet__receive_internal_simple_2687_97 --> JettonDefaultWallet__receive_internal_simple_2687_98
    JettonDefaultWallet__receive_internal_simple_2687_98 --> JettonDefaultWallet__receive_internal_simple_2687_99
    JettonDefaultWallet__receive_internal_simple_2687_99 --> JettonDefaultWallet__receive_internal_simple_2687_100
    JettonDefaultWallet__receive_internal_simple_2687_100 --> JettonDefaultWallet__receive_internal_simple_2687_101
    JettonDefaultWallet__receive_internal_simple_2687_101 --> JettonDefaultWallet__receive_internal_simple_2687_102
    JettonDefaultWallet__receive_internal_simple_2687_102 --> JettonDefaultWallet__receive_internal_simple_2687_103
    JettonDefaultWallet__receive_internal_simple_2687_103 --> JettonDefaultWallet__receive_internal_simple_2687_104
    JettonDefaultWallet__receive_internal_simple_2687_104 --> JettonDefaultWallet__receive_internal_simple_2687_105
    JettonDefaultWallet__receive_internal_simple_2687_105 --> JettonDefaultWallet__receive_internal_simple_2687_106
    JettonDefaultWallet__receive_internal_simple_2687_106 --> JettonDefaultWallet__receive_internal_simple_2687_107
    JettonDefaultWallet__receive_internal_simple_2687_107 --> JettonDefaultWallet__receive_internal_simple_2687_108
end
subgraph JettonDefaultWallet__msgValue
    JettonDefaultWallet__msgValue_109["let tonBalanceBeforeMsg: Int = myBalance() - value"]
    JettonDefaultWallet__msgValue_110["let storageFee: Int = self.minTonsForStorage - min(tonBalanceBeforeMsg, self.minTonsForStorage)"]
    JettonDefaultWallet__msgValue_111["value -= storageFee + self.gasConsumption"]
    JettonDefaultWallet__msgValue_112["return value"]:::exitNode
    JettonDefaultWallet__msgValue_109 --> JettonDefaultWallet__msgValue_110
    JettonDefaultWallet__msgValue_110 --> JettonDefaultWallet__msgValue_111
    JettonDefaultWallet__msgValue_111 --> JettonDefaultWallet__msgValue_112
end
subgraph JettonDefaultWallet__receive_internal_simple_2832
    JettonDefaultWallet__receive_internal_simple_2832_113["let ctx: Context = context()"]
    JettonDefaultWallet__receive_internal_simple_2832_114["require(ctx.sender == self.owner, 'Invalid sender')"]
    JettonDefaultWallet__receive_internal_simple_2832_115["self.balance = self.balance - msg.amount"]
    JettonDefaultWallet__receive_internal_simple_2832_116["require(self.balance &gt;= 0, 'Invalid balance')"]
    JettonDefaultWallet__receive_internal_simple_2832_117["let fwdFee: Int = ctx.readForwardFee()"]
    JettonDefaultWallet__receive_internal_simple_2832_118["require(ctx.value &gt; fwdFee + 2 * self.gasConsumption + self.minTonsForStorage, 'Invalid value - Burn')"]
    JettonDefaultWallet__receive_internal_simple_2832_119["send(SendParameters{to: self.master, value: 0, mode: SendRemainingValue, bounce: true, body: TokenBurnNotification{queryId: msg.queryId, amount: msg.amount, owner: self.owner, response_destination: self.owner}.toCell()})"]:::exitNode
    JettonDefaultWallet__receive_internal_simple_2832_113 --> JettonDefaultWallet__receive_internal_simple_2832_114
    JettonDefaultWallet__receive_internal_simple_2832_114 --> JettonDefaultWallet__receive_internal_simple_2832_115
    JettonDefaultWallet__receive_internal_simple_2832_115 --> JettonDefaultWallet__receive_internal_simple_2832_116
    JettonDefaultWallet__receive_internal_simple_2832_116 --> JettonDefaultWallet__receive_internal_simple_2832_117
    JettonDefaultWallet__receive_internal_simple_2832_117 --> JettonDefaultWallet__receive_internal_simple_2832_118
    JettonDefaultWallet__receive_internal_simple_2832_118 --> JettonDefaultWallet__receive_internal_simple_2832_119
end
subgraph JettonDefaultWallet__receive_bounce_2876
    JettonDefaultWallet__receive_bounce_2876_120["let op: Int = msg.loadUint(32)"]
    JettonDefaultWallet__receive_bounce_2876_121["let queryId: Int = msg.loadUint(64)"]
    JettonDefaultWallet__receive_bounce_2876_122["let jettonAmount: Int = msg.loadCoins()"]
    JettonDefaultWallet__receive_bounce_2876_123["require(op == 0x178d4519 || op == 0x7bdd97de, 'Invalid bounced message')"]
    JettonDefaultWallet__receive_bounce_2876_124["self.balance = self.balance + jettonAmount"]:::exitNode
    JettonDefaultWallet__receive_bounce_2876_120 --> JettonDefaultWallet__receive_bounce_2876_121
    JettonDefaultWallet__receive_bounce_2876_121 --> JettonDefaultWallet__receive_bounce_2876_122
    JettonDefaultWallet__receive_bounce_2876_122 --> JettonDefaultWallet__receive_bounce_2876_123
    JettonDefaultWallet__receive_bounce_2876_123 --> JettonDefaultWallet__receive_bounce_2876_124
end
subgraph JettonDefaultWallet__get_wallet_data
    JettonDefaultWallet__get_wallet_data_125["return JettonWalletData{balance: self.balance, owner: self.owner, master: self.master, walletCode: initOf JettonDefaultWallet(self.master, self.owner).code}"]:::exitNode
end
