graph TD
    node_1["test_try"]
    node_2["test_loops"]
    node_3["TestContract::getter"]
    node_4["TestContractF::test"]
    node_5["TestContractT::test"]
    node_6["TestContractT::receiver_1722"]
    node_7["dump"]
    node_8["emptyMap"]
    node_9["TestContractT::getA"]
    node_1 --> node_7
    node_2 --> node_8
    node_5 --> node_9
