graph TD
    node_10["inline fun random(min: Int, max: Int): Int"]
    node_17["inline fun newAddress(chain: Int, hash: Int): Address"]
    node_22["fun test_try(a: Int)"]
    node_23["fun test_loops()"]
    node_24["fun testTryCatch(a: Int)"]
    node_25["fun testLoops()"]
    node_26["fun callAsm(s: Slice): Cell"]
    node_27["extends fun String::toInt(self: String): Int"]
    node_28["override get fun TestContract::getter(): Int"]
    node_29["get fun Z::getter(): Int
[StateRead<a>]"]
    node_30["fun TestContractF::test()"]
    node_31["fun TParent::getA(): Int
[StateRead<a>]"]
    node_32["fun TestContractT::test(): Int"]
    node_33["TestContractT::external()"]
    node_34["EffectTest::init()
[StateWrite<addr,b,s>]"]
    node_35["fun EffectTest::funcWithSend()
[Send,StateRead<addr>]"]
    node_36["fun EffectTest::funcWithStateRead()
[StateRead<addr>]"]
    node_37["fun EffectTest::funcWithStateWrite1()
[StateRead<b,addr,s>,StateWrite<addr>]"]
    node_38["fun EffectTest::funcWithStateWrite2(s: Slice): Address"]
    node_39["fun EffectTest::funcWithMultipleEffects()
[AccessDatetime,PrgUse,PrgSeedInit]"]
    node_40["EffectTest::receive()"]
    node_41["get fun A::m(): map<Int, Int>
[StateRead<m>]"]
    node_42["A::receive()
[StateRead<m>]"]
    node_46["dump"]
    node_47["emptyMap"]
    node_48["m::set"]
    node_49["s::loadRefEx"]
    node_50["String::asSlice"]
    node_51["string::empty"]
    node_52["string::loadUint"]
    node_53["TestContractT::getA"]
    node_54["sender"]
    node_55["beginCell"]
    node_56["send"]
    node_57["s::loadAddress"]
    node_58["now"]
    node_59["nativeRandomizeLt"]
    node_60["beginString"]
    node_61["a::append"]
    node_22 --> node_46
    node_23 --> node_47
    node_24 --> node_46
    node_25 --> node_47
    node_25 --> node_48
    node_25 --> node_48
    node_25 --> node_48
    node_26 --> node_49
    node_27 --> node_50
    node_27 --> node_51
    node_27 --> node_52
    node_32 --> node_53
    node_34 --> node_54
    node_34 --> node_55
    node_35 --> node_56
    node_37 --> node_17
    node_38 --> node_57
    node_39 --> node_58
    node_39 --> node_10
    node_39 --> node_59
    node_40 --> node_60
    node_40 --> node_61
    style node_10 fill:#F0F8FF,stroke:#000,stroke-width:1px;
    style node_17 fill:#F0F8FF,stroke:#000,stroke-width:1px;
