graph TD
    node_12["inline fun random(min: Int, max: Int): Int"]
    node_15["fun send(params: SendParameters): Int"]
    node_17["fun test_try(a: Int)"]
    node_18["fun test_loops()"]
    node_19["fun testTryCatch(a: Int)"]
    node_20["fun testLoops()"]
    node_21["fun callAsm(s: Slice): Cell"]
    node_22["override get fun getter(): Int"]
    node_23["fun test()"]
    node_24["fun test(): Int"]
    node_25["external()"]
    node_26["init()
[StateWrite]"]
    node_27["fun funcWithSend()
[Send,StateRead]"]
    node_28["fun funcWithStateRead()
[StateRead]"]
    node_29["fun funcWithStateWrite()
[StateWrite]"]
    node_30["fun funcWithMultipleEffects()
[AccessDatetime,PrgUse,PrgSeedInit]"]
    node_31["receive()"]
    node_32["dump"]
    node_33["emptyMap"]
    node_34["m::set"]
    node_35["s::loadRefEx"]
    node_36["getA"]
    node_37["sender"]
    node_38["newAddress"]
    node_39["now"]
    node_40["nativeRandomizeLt"]
    node_41["beginString"]
    node_42["a::append"]
    node_17 --> node_32
    node_18 --> node_33
    node_19 --> node_32
    node_20 --> node_33
    node_20 --> node_34
    node_20 --> node_34
    node_20 --> node_34
    node_21 --> node_35
    node_24 --> node_36
    node_26 --> node_37
    node_27 --> node_15
    node_29 --> node_38
    node_30 --> node_39
    node_30 --> node_12
    node_30 --> node_40
    node_31 --> node_41
    node_31 --> node_42
