graph TD
subgraph TestContract__getter
    TestContract__getter_68["return 0"]:::exitNode
end
subgraph TestContractF__test
end
subgraph TestContractT__test
    TestContractT__test_69["return self.getA()"]:::exitNode
end
