import { MistiContext } from "../internals/context";
import { CompilationUnit } from "../internals/ir";
import { makeDocURL, MistiTactError, Severity } from "../internals/errors";
import { SrcInfo } from "@tact-lang/compiler/dist/grammar/ast";
import {
  Context as SouffleContext,
  Fact,
  FactValue,
  Executor,
} from "../internals/souffle";

export type WarningsBehavior = "union" | "intersect";

export type DetectorName = string;

/**
 * Abstract base class for a detector module, providing an interface for defining various types of detectors.
 */
export abstract class Detector {
  constructor(readonly ctx: MistiContext) {}

  /**
   * Gets the short identifier of the detector, used in analyzer warnings.
   * @returns The unique identifier of the detector.
   */
  get id(): DetectorName {
    return this.constructor.name;
  }

  /**
   * Defines the behavior of warnings generated by this detector when working with
   * multiple projects within a single Tact configuration.
   *
   * Here are the available options:
   * 1. `"union"`
   * Leave this value if you don't care about warnings generated in other projects.
   * 2. `"intersect"`
   * If the warning is generated for some source location of the imported file,
   * it should be generated by each of the projects. Example: Constants from an
   * imported file should not be reported iff they are unused in all the projects,
   * so you need "intersect".
   */
  public get shareImportedWarnings(): WarningsBehavior {
    return "union";
  }

  /**
   * Executes Souffle program for this detector converting output facts to warnings.
   * @param program Souffle context with all the declarations, rules and facts added.
   * @param callback A function that creates warnings from output facts.
   */
  protected executeSouffle(
    program: SouffleContext<SrcInfo>,
    callback: (fact: Fact<FactValue, SrcInfo>) => MistiTactError | undefined,
  ): MistiTactError[] {
    const executor = this.ctx.config.soufflePath
      ? new Executor<SrcInfo>({
          inputDir: this.ctx.config.soufflePath,
          outputDir: this.ctx.config.soufflePath,
        })
      : new Executor<SrcInfo>();
    const result = executor.executeSync(program);
    if (!result.success) {
      throw new Error(
        `Error executing Soufflé for ${this.id}:\n${result.stderr}`,
      );
    }
    return Array.from(result.results.entries.values()).reduce<MistiTactError[]>(
      (acc, facts) => {
        return acc.concat(
          facts.reduce<MistiTactError[]>((innerAcc, fact) => {
            const error = callback(fact);
            if (error) {
              innerAcc.push(error);
            }
            return innerAcc;
          }, []),
        );
      },
      [],
    );
  }

  /**
   * Executes the detector's logic to check for issues within the provided compilation unit.
   * @param cu The compilation unit to be analyzed.
   * @returns List of errors has highlighted by this detector.
   */
  abstract check(cu: CompilationUnit): MistiTactError[];

  /**
   * Returns `true` if the identifier with the given name should not be reported
   * by unused variables detectors.
   */
  protected skipUnused(name: string): boolean {
    return name.startsWith(this.ctx.config.unusedPrefix);
  }

  /**
   * A wrapper method that creates Misti errors with additional context about
   * the detector generated it.
   */
  protected makeError(
    description: string,
    severity: Severity,
    loc: SrcInfo,
    data: Partial<{
      extraDescription: string;
      suggestion: string;
    }> = {},
  ): MistiTactError {
    return MistiTactError.make(this.ctx, this.id, description, severity, loc, {
      ...data,
      docURL: makeDocURL(this.id),
    });
  }
}

// Define the structure of each detector entry in the BuiltInDetectors map.
interface DetectorEntry {
  loader: (ctx: MistiContext) => Promise<Detector>;
  enabledByDefault: boolean;
}

/**
 * A mapping of detector names to their respective loader functions and default enablement status.
 */
const BuiltInDetectors: Record<string, DetectorEntry> = {
  DivideBeforeMultiply: {
    loader: (ctx: MistiContext) =>
      import("./builtin/divideBeforeMultiply").then(
        (module) => new module.DivideBeforeMultiply(ctx),
      ),
    enabledByDefault: true,
  },
  ReadOnlyVariables: {
    loader: (ctx: MistiContext) =>
      import("./builtin/readOnlyVariables").then(
        (module) => new module.ReadOnlyVariables(ctx),
      ),
    enabledByDefault: true,
  },
  NeverAccessedVariables: {
    loader: (ctx: MistiContext) =>
      import("./builtin/neverAccessedVariables").then(
        (module) => new module.NeverAccessedVariables(ctx),
      ),
    enabledByDefault: true,
  },
  UnboundLoops: {
    loader: (ctx: MistiContext) =>
      import("./builtin/unboundLoops").then(
        (module) => new module.UnboundLoops(ctx),
      ),
    enabledByDefault: true,
  },
  ZeroAddress: {
    loader: (ctx: MistiContext) =>
      import("./builtin/zeroAddress").then(
        (module) => new module.ZeroAddress(ctx),
      ),
    enabledByDefault: true,
  },
  ConstantAddress: {
    loader: (ctx: MistiContext) =>
      import("./builtin/constantAddress").then(
        (module) => new module.ConstantAddress(ctx),
      ),
    enabledByDefault: false,
  },
};

/**
 * Asynchronously retrieves a built-in detector by its name.
 * If the detector is found in the BuiltInDetectors registry, it is loaded and returned;
 * otherwise, a warning is logged and `undefined` is returned.
 *
 * @param ctx Misti context.
 * @param name The name of the detector to retrieve. This name must match a key in the BuiltInDetectors object.
 * @returns A Promise that resolves to a Detector instance or `undefined` if the detector cannot be found or fails to load.
 */
export async function findBuiltInDetector(
  ctx: MistiContext,
  name: string,
): Promise<Detector | undefined> {
  const detectorEntry = BuiltInDetectors[name];
  if (!detectorEntry) {
    ctx.logger.warn(`Built-in detector ${name} not found.`);
    return undefined;
  }
  try {
    return await detectorEntry.loader(ctx);
  } catch (error) {
    ctx.logger.error(`Error loading built-in detector ${name}: ${error}`);
    return undefined;
  }
}

/**
 * Returns a list of all the available built-in detectors.
 * @returns An array of strings representing the names of detectors.
 */
export function getAllDetectors(): string[] {
  return Object.keys(BuiltInDetectors);
}

/**
 * Returns a list of detector names that are enabled by default.
 * @returns An array of strings representing the names of enabled detectors.
 */
export function getEnabledDetectors(): string[] {
  return Object.keys(BuiltInDetectors).filter(
    (name) => BuiltInDetectors[name].enabledByDefault,
  );
}
